### ISSUE TITLE
Client crashes on mouseover interaction

### ISSUE THREAD

**Issue by jermangarc** [hilburn/StevesAddons#23]
http://pastebin.com/F6BBE5yK

**Comment by jermangarc** [comment]
Using latest StevesAddons-1.7.10-0.9.11

**Comment by hilburn** [comment]
What were you mousing over?

**Comment by hilburn** [comment]
Fixed in 0.9.12

**Comment by jermangarc** [comment]
I'll have to check with my user. He was the one using it, so I'll have to ask him.

**Comment by hilburn** [comment]
Ok - closing this, but would still like to know if possible

**Comment by gazpachoking** [comment]
I just came to report this issue. For me it was an Ender Tank.

**Comment by gazpachoking** [comment]
Still getting the crash on 0.9.12 with the ender tank with water in.
https://gist.github.com/gazpachoking/97d33e86280f9f6f7c2f

**Comment by hilburn** [comment]
This appears to actually be a different issue because EnderTanks appear to be doing weird things. Such is life. Is fixed and will be up shortly

**Comment by gazpachoking** [comment]
Looking go so far, thanks!
